@baseUrl = http://localhost:5000

### Health Check
GET {{baseUrl}}/health
Accept: application/json

### Get All Clients
GET {{baseUrl}}/api/clients
Accept: application/json

### Create New Client
POST {{baseUrl}}/api/clients
Content-Type: application/json
{
  "name": "New Client",
  "webSite": "https://newclient.com",
   "notes": "This is a new client."
}

### Get Client by ID
@clientId = 2
GET {{baseUrl}}/api/clients/{{clientId}}
Accept: application/json

### Update Client
@clientIdToUpdate = 2
PUT {{baseUrl}}/api/clients/{{clientIdToUpdate}}
Content-Type: application/json
{
  "name": "Updated Client",
  "webSite": "https://updatedclient.com",
   "notes": "Updated client."
}

### Delete Client
@clientIdToDelete = 2
DELETE {{baseUrl}}/api/clients/{{clientIdToDelete}}
Accept: application/json
